### ISSUE TITLE
Changes to yolo layer

### ISSUE THREAD

**Issue by philipp-schmidt** [upczww/yolov5-tensorrt-batchednms#10]
Hi, great work, thx for open sourcing it. Can you quickly outline what you had to change in the yolo layer to make it work with the BatchedNMS plugin? I would like to add this to my YOLOv4 implementation as well (it's also tensorrtx based) and I think it's very similar.

https://github.com/isarsoft/yolov4-triton-tensorrt

I'm using a slightly different version of the yolo layer from [tensort_demo](https://github.com/jkjung-avt/tensorrt_demos) which was improved by the author there, so it's not exactly the same anymore.

Would love to hear what you think.

**Comment by upczww** [comment]
You can compare my implement of  yololayer.h and yololayer.cu with [tensorrtx](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5).
